services:
- docker
language: node_js
node_js:
- '10'
script:
- yarn lint
- yarn test:compose
env:
  global:
    secure: OyP8ZujJwl/LsYWhiWFqG4won6k9ZYk11XZCvJPNm1W6U47aYuT5LYOjlDUeUHWPugI1Fl00PhND0CtXMASqX9QZA3zwHO2NHjxYRHSkdUMWkPYASk2AHXjpqh+5KOguprzK853pVE3vIRgh0Q8SKjwi9rGPpTfXC3kcQVL2PamdAZ5CVt535OtVQ4F7CYQ+fq1IRSdCVls4foY1+9LX/+Ko9cJ6bgRFVdkn3mgU5qx4TMuzoLM6j9O+lFTi34/h3yehThxLwi36J6LpGZLCg9WeCMzEkhAApp4CcHUz2wGXEarSC5K5ABs/VYpQ4IgvXLWhvymX1EXg04OZEdePd+yFmkkxqzqsCgmi/Kdb+DMDKw+s4NgJX4ikHHOct6qaPO9i9Dy1keyweQbsZVfIf6GAAtc18FIuTf/Lx8sjUwqwHpzLIfSq0hgXH24WUuQMKTwf1ggI4jB53/lloYiR8kGtarn7a+6u4Khu2FWZlDcacB6VkZWfMW2lRU6IUE/zKXE0MOQE8q4vF7PEY3cEkp563fr1bJ7pU6WV4n85uxMnrYitHkxd28oBkHSPw3n/1PRgvOuMse4dUZWT8UWeivL0wG3S4j9VW1qS0I8o7KM6I+tQVBGssSJxaQF/l727QPZ4Cx5KpEnS0C8z72KxIlU8OzvNWjH9cmPRRoW8GTE=
