version: '1'

services:

  eq-author:
      image: onsdigital/eq-author
      environment:
        - REACT_APP_BASE_NAME = /eq-author
        - REACT_APP_API_URL = http://localhost:4000/graphql
        - REACT_APP_USE_MOCK_API = "false"
        - REACT_APP_PUBLISHER_URL = http://eq-publisher:9000/publish
        - REACT_APP_GO_LAUNCH_A_SURVEY_URL = http://localhost:8000/quick-launch
        - REACT_APP_ENABLE_AUTH
        - REACT_APP_FIREBASE_PROJECT_ID
        - REACT_APP_FIREBASE_API_KEY
        - REACT_APP_FIREBASE_MESSAGING_SENDER_ID
      depends_on:
        - eq-author-api
        - eq-survey-launcher
      restart: always
      networks:
        - eq-author
      ports:
        - 3000:3000