version: '3'

services:

  eq-author:
    image: onsdigital/eq-author
    ports:
      - 3000:3000
    restart: always
    networks:
      - eq-author
    env_file: 
      - eq-author.env
    environment:
      REACT_APP_FIREBASE_PROJECT_ID: 
      REACT_APP_FIREBASE_API_KEY:

  eq-author-api:
    image: onsdigital/eq-author-api
    ports:
      - 4000:4000
    restart: always
    networks:
      - eq-author
    env_file:
      - eq-author-api.env
    environment: 
      FIREBASE_PROJECT_ID:

  eq-publisher:
    image: onsdigital/eq-publisher
    ports:
      - 9000:9000
    restart: always
    networks:
      - eq-author
      - eq-runner
    env_file: eq-publisher.env

  eq-survey-runner:
    image: onsdigital/eq-survey-runner
    ports:
      - 5000:5000
    networks:
      - eq-runner
    restart: always
    env_file: eq-survey-runner.env

  eq-schema-validator:
    image: onsdigital/eq-schema-validator
    restart: always
    ports:
      - 5001:5000
    networks:
      - eq-author
      - eq-runner

  eq-survey-runner-dynamodb:
    image: onsdigital/eq-docker-dynamodb:latest
    ports:
      - 6060:8000
    networks:
      - eq-runner
    restart: always

  eq-survey-runner-db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: digitaleq
      POSTGRES_USER: digitaleq
      POSTGRES_DB: runner
    restart: always
    networks:
      - eq-runner
    ports:
      - 5432:5432

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - eq-author
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    networks:
      - eq-author
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    networks:
      - eq-author
    restart: always

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    networks:
      - eq-runner
    environment: 
      RABBITMQ_DEFAULT_USER: digitaleq
      RABBITMQ_DEFAULT_PASS: digitaleq

networks:
  eq-runner:
    driver: bridge
  eq-author:
    driver: bridge